"""Closed Secure Certificate Capture V1 lifecycle values."""

from __future__ import annotations

from enum import Enum


class CaptureStateV1(str, Enum):
    """The complete normative V1 capture lifecycle.

    Milestone 4B activates CAPTURING and, only with a constructor-injected test
    processor, BUILDING_ASSERTIONS and READY. Production post-seal processing
    remains unavailable and fails closed rather than publishing fake readiness.
    """

    IDLE = "IDLE"
    ENTERING = "ENTERING"
    QUIESCING = "QUIESCING"
    ARMED = "ARMED"
    CAPTURING = "CAPTURING"
    BUILDING_ASSERTIONS = "BUILDING_ASSERTIONS"
    READY = "READY"
    ENDING = "ENDING"
    FAILED_CLOSED = "FAILED_CLOSED"


class CaptureTransitionKindV1(str, Enum):
    BEGIN = "BEGIN"
    END = "END"


class CaptureTransitionPhaseV1(str, Enum):
    CLAIMED = "CLAIMED"
    RETIRING = "RETIRING"
    CLEANING = "CLEANING"
    VERIFYING = "VERIFYING"


class CaptureFailureReasonV1(str, Enum):
    FEATURE_DISABLED = "FEATURE_DISABLED"
    SESSION_AUTHORITY_UNAVAILABLE = "SESSION_AUTHORITY_UNAVAILABLE"
    SECURITY_AUTHORITY_UNAVAILABLE = "SECURITY_AUTHORITY_UNAVAILABLE"
    WORK_CONTROLLER_UNAVAILABLE = "WORK_CONTROLLER_UNAVAILABLE"
    INVALID_STATE = "INVALID_STATE"
    CAPTURE_BUSY = "CAPTURE_BUSY"
    CAPTURE_EPOCH_MISMATCH = "CAPTURE_EPOCH_MISMATCH"
    CAPTURE_SEQUENCE_MISMATCH = "CAPTURE_SEQUENCE_MISMATCH"
    CAPTURE_SEQUENCE_OVERFLOW = "CAPTURE_SEQUENCE_OVERFLOW"
    STALE_TRANSITION = "STALE_TRANSITION"
    GENERATION_MISMATCH = "GENERATION_MISMATCH"
    GENERATION_RETIREMENT_FAILED = "GENERATION_RETIREMENT_FAILED"
    QUIESCENCE_DRAIN_FAILED = "QUIESCENCE_DRAIN_FAILED"
    QUIESCENCE_TIMEOUT = "QUIESCENCE_TIMEOUT"
    SEMANTIC_CLEANUP_FAILED = "SEMANTIC_CLEANUP_FAILED"
    CLEANUP_TIMEOUT = "CLEANUP_TIMEOUT"
    RESUME_BARRIER_FAILED = "RESUME_BARRIER_FAILED"
    SESSION_SHUTDOWN = "SESSION_SHUTDOWN"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"


class CaptureTransitionPointV1(str, Enum):
    """Deterministic test-only observation points."""

    AFTER_ENTERING = "AFTER_ENTERING"
    BEFORE_BEGIN_RETIREMENT = "BEFORE_BEGIN_RETIREMENT"
    AFTER_BEGIN_RETIREMENT = "AFTER_BEGIN_RETIREMENT"
    AFTER_QUIESCING = "AFTER_QUIESCING"
    BEFORE_ARMED = "BEFORE_ARMED"
    AFTER_ENDING = "AFTER_ENDING"
    BEFORE_END_RETIREMENT = "BEFORE_END_RETIREMENT"
    AFTER_END_RETIREMENT = "AFTER_END_RETIREMENT"
    BEFORE_RESUME = "BEFORE_RESUME"


__all__ = [
    "CaptureFailureReasonV1",
    "CaptureStateV1",
    "CaptureTransitionKindV1",
    "CaptureTransitionPhaseV1",
    "CaptureTransitionPointV1",
]
